services:
  directory-service:
    image: sebastianbran/poc-cce-demo-directory-service:latest
    ports:
      - "8080:8080"

  transaction-service:
    image: sebastianbran/poc-cce-demo-transaction-service:latest
    environment:
      REST_CLIENT_DIRECTORY_SERVICE: http://directory-service:8080
      REST_CLIENT_NOTIFICATION_SERVICE: http://notification-service:8080
    ports:
      - "8081:8080"

  notification-service:
    image: sebastianbran/poc-cce-demo-notification-service:latest
    ports:
      - "8082:8080"