apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: sebastianbran/poc-cce-demo-transaction-service:latest
          env:
            - name: REST_CLIENT_DIRECTORY_SERVICE
              value: http://directory-service-svc:8080
            - name: REST_CLIENT_NOTIFICATION_SERVICE
              value: http://notification-service-svc:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-svc
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
